
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true


org.gradle.configuration-cache=false



minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.17-SNAPSHOT


mod_version=1.1
maven_group=com.botato.autokeystrokes
archives_base_name=autokeystrokes


fabric_version=0.151.0+26.1.2
org.gradle.java.installations.paths=C:/Program Files/Microsoft/jdk-25.0.3.9-hotspot
